# Generated by Django 4.0.4 on 2022-05-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Banner_photo',
            new_name='banner_photo',
        ),
    ]
