# Generated by Django 4.0.4 on 2022-05-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='social_link',
            field=models.URLField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
