# Generated by Django 4.0.4 on 2022-05-25 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_bio_alter_customuser_social_link'),
        ('users', '0007_customuser_coffee_customuser_mentoring_and_more'),
    ]

    operations = [
    ]
