# Generated by Django 4.0.4 on 2022-05-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_date_created_articles_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
