# Generated by Django 4.0.4 on 2022-05-28 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_remove_articles_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='articles.articles')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporter_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
