# Generated by Django 4.0.4 on 2022-05-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ManyToManyField(related_name='articles', related_query_name='articles', to='articles.category'),
        ),
    ]
